services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - DATABASE_URL=postgres://pguser:pgpassword@localhost:5480/pgdb
    ports:
      - "5480:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-db:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
