# Generated by Django 5.2.7 on 2025-10-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brightdatasnapshot",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
