# Generated by Django 5.2.7 on 2025-10-20 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0003_brightdatasnapshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
