# Generated by Django 5.2.7 on 2025-10-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snapshots", "0004_brightdatasnapshot_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brightdatasnapshot",
            name="progress_check_count",
            field=models.IntegerField(default=0),
        ),
    ]
