# Generated by Django 5.2.7 on 2025-10-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapshots', '0006_brightdatasnapshot_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='_status',
            field=models.CharField(default='unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='brightdatasnapshot',
            name='last_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brightdatasnapshot',
            name='status',
            field=models.CharField(default='unknown', max_length=120),
        ),
    ]
