# Generated by Django 5.2.7 on 2025-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditpost",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
