# Generated by Django 5.2.7 on 2025-10-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_redditpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
