# Generated by Django 5.2.7 on 2025-10-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0003_redditpost_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditpost",
            name="related_posts",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
