# Generated by Django 5.2.7 on 2025-10-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0004_redditpost_related_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditpost",
            name="community_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="redditpost",
            name="num_upvotes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
