# Generated by Django 5.2.7 on 2025-10-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0005_redditpost_community_name_redditpost_num_upvotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditpost",
            name="num_comments",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
