# Generated by Django 5.2.7 on 2025-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0006_redditpost_num_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditpost",
            name="title",
            field=models.CharField(blank=True, null=True),
        ),
    ]
