# Generated by Django 5.2.7 on 2025-10-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0007_alter_redditpost_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditCommunitySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="The complete URL of the Reddit community",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True, help_text="Formatted name for Reddit", null=True
                    ),
                ),
                (
                    "subreddit_slug",
                    models.CharField(
                        blank=True,
                        help_text="The slug of the subreddit, such as r/Python, r/web, or r/trending",
                        max_length=400,
                        null=True,
                    ),
                ),
                (
                    "member_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Current member count, if available",
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Is this searchable?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
