# Generated by Django 5.2.7 on 2025-10-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0008_redditcommunityschema"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RedditCommunitySchema",
            new_name="RedditCommunity",
        ),
    ]
