# Generated by Django 5.2.7 on 2025-10-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reddit", "0009_rename_redditcommunityschema_redditcommunity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redditcommunity",
            options={"verbose_name_plural": "reddit communities"},
        ),
        migrations.AddField(
            model_name="redditcommunity",
            name="last_scrape_event",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="redditpost",
            name="date_posted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
